#!/usr/bin/env bash

set -euo pipefail


# ============================================================
# LOCAL PATHS
# ============================================================

PROJECT_DIR="${PROJECT_DIR:-$HOME/Documents/GitHub/TradingMage}"

APP_DIR="${APP_DIR:-$PROJECT_DIR/app}"

VENV_DIR="${VENV_DIR:-$PROJECT_DIR/.plot_venv}"

ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env.local-backtest}"


# ============================================================
# EC2 / SSH
# ============================================================

SSH_KEY="${SSH_KEY:-$HOME/.ssh/my-aws-ec2-key}"

EC2_USER="${EC2_USER:-ubuntu}"

EC2_HOST="${EC2_HOST:-54.176.151.9}"


# ============================================================
# REDIS
#
# Server-side Redis URL is effectively:
#
# redis://redis:6379/0
#
# "redis" is a Docker-network hostname and cannot be resolved
# directly by the Mac.
#
# This script discovers the Redis container IP on EC2 and
# tunnels a local Mac port to that container IP.
# ============================================================

REMOTE_REDIS_CONTAINER="${REMOTE_REDIS_CONTAINER:-redis}"

REMOTE_REDIS_PORT="${REMOTE_REDIS_PORT:-6379}"

REDIS_DATABASE="${REDIS_DATABASE:-0}"

LOCAL_REDIS_PORT="${LOCAL_REDIS_PORT:-16379}"


# ============================================================
# LOCAL FASTAPI
# ============================================================

LOCAL_APP_HOST="${LOCAL_APP_HOST:-127.0.0.1}"

LOCAL_APP_PORT="${LOCAL_APP_PORT:-8000}"


# ============================================================
# LOCAL OUTPUTS
#
# Everything generated by this script goes under:
#
# TradingMage/local_backtest_output/
#
# unless an absolute OUTPUT_FILE path is explicitly supplied.
# ============================================================

OUTPUT_DIR="${OUTPUT_DIR:-$PROJECT_DIR/local_backtest_output}"

RESEARCH_LOG="${RESEARCH_LOG:-$OUTPUT_DIR/backtest_factor_research.jsonl}"

UVICORN_LOG="${UVICORN_LOG:-$OUTPUT_DIR/local_backtest_uvicorn.log}"

EXTRACT_ZIP="${EXTRACT_ZIP:-true}"


# ============================================================
# HELP
# ============================================================

usage() {

	cat <<'EOF'

TradingMage Local Endpoint Runner

Usage:

	./run_local_endpoint.sh ENDPOINT [name=value ...]


Available endpoint aliases:

	run
		GET /backtest/run

	plot
		GET /backtest/plot

	research-plot
		GET /backtest/factor-research/plot

	research-groups
		GET /backtest/factor-research/groups

	research-delete
		DELETE /backtest/factor-research


============================================================
EXAMPLES
============================================================


NORMAL BACKTEST

	./run_local_endpoint.sh run \
		strategy_name=strategy4_1h_anchor \
		start=2026-05-31T04:00:00-04:00 \
		end=2026-08-07T20:00:00-04:00 \
		position_size=6600 \
		exit_strategy=4 \
		loss_liquidation_atr_factor=0.6 \
		liquidate_before_market_close=true


EXIT STRATEGY 3 BACKTEST

	./run_local_endpoint.sh run \
		strategy_name=strategy4_1h_anchor \
		start=2026-05-31T04:00:00-04:00 \
		end=2026-08-07T20:00:00-04:00 \
		position_size=6600 \
		ATR_period=14 \
		ATR_multiplier=0.8 \
		exit_strategy=3 \
		loss_liquidation_atr_factor=0.6 \
		profit_expansion_atr_factor=2.5 \
		trailing_stop_multiplier_factor=1.8 \
		liquidate_before_market_close=true


RESEARCH RUN

	./run_local_endpoint.sh run \
		strategy_name=strategy4_1h_anchor \
		start=2026-05-31T04:00:00-04:00 \
		end=2026-08-07T20:00:00-04:00 \
		position_size=6600 \
		exit_strategy=4 \
		loss_liquidation_atr_factor=0.3 \
		liquidate_before_market_close=true \
		record_factor_research=true \
		research_group_id=strategy4_1h_20260531_20260807_v1


BACKTEST PLOT

	./run_local_endpoint.sh plot \
		strategy_name=strategy4_1h_anchor \
		start=2026-05-31T04:00:00-04:00 \
		end=2026-08-07T20:00:00-04:00 \
		position_size=6600 \
		ATR_multiplier=0.8 \
		exit_strategy=3 \
		loss_liquidation_atr_factor=0.6 \
		profit_expansion_atr_factor=2.5 \
		trailing_stop_multiplier_factor=1.8 \
		liquidate_before_market_close=true


FACTOR-RESEARCH PLOT

	./run_local_endpoint.sh research-plot \
		research_group_id=strategy4_1h_20260531_20260807_v1 \
		require_all_factors=true \
		pnl_tie_tolerance=0.01 \
		minimum_pnl_margin=0.01


LIST RESEARCH GROUPS

	./run_local_endpoint.sh research-groups


DELETE ONE RESEARCH GROUP

	./run_local_endpoint.sh research-delete \
		research_group_ids=strategy4_1h_20260531_20260807_v1


DELETE MULTIPLE RESEARCH GROUPS

	./run_local_endpoint.sh research-delete \
		research_group_ids=strategy4_test_v1,strategy4_test_v2,strategy4_test_v3


DELETE ALL LOCAL RESEARCH DATA

	./run_local_endpoint.sh research-delete \
		delete_all=true \
		confirm=true


CUSTOM OUTPUT FILE

	OUTPUT_FILE=my_result.json \
	./run_local_endpoint.sh run \
		strategy_name=strategy4_1h_anchor \
		start=2026-08-01T04:00:00-04:00 \
		end=2026-08-07T20:00:00-04:00


DON'T AUTOMATICALLY EXTRACT ZIP

	EXTRACT_ZIP=false \
	./run_local_endpoint.sh plot \
		strategy_name=strategy4_1h_anchor \
		start=2026-08-01T04:00:00-04:00 \
		end=2026-08-07T20:00:00-04:00


============================================================

Everything after ENDPOINT must use:

	name=value

The arguments are URL-encoded and passed directly to the actual
FastAPI endpoint.

FastAPI/app.py remains the source of truth for:

	- parameter names
	- required parameters
	- optional parameters
	- defaults
	- type validation

Generated files default to:

	TradingMage/local_backtest_output/

EOF

}


# ============================================================
# REQUIRE ENDPOINT
# ============================================================

if [[ $# -lt 1 ]]; then

	usage

	exit 1

fi


ENDPOINT_INPUT="$1"

shift


# ============================================================
# ENDPOINT DEFINITIONS
# ============================================================

case "$ENDPOINT_INPUT" in

	run)

		HTTP_METHOD="GET"

		ENDPOINT="/backtest/run"

		OUTPUT_TYPE="json"

		DEFAULT_OUTPUT_FILE="$OUTPUT_DIR/backtest.json"

		;;


	plot)

		HTTP_METHOD="GET"

		ENDPOINT="/backtest/plot"

		OUTPUT_TYPE="zip"

		DEFAULT_OUTPUT_FILE="$OUTPUT_DIR/backtest_charts.zip"

		;;


	research-plot)

		HTTP_METHOD="GET"

		ENDPOINT="/backtest/factor-research/plot"

		OUTPUT_TYPE="zip"

		DEFAULT_OUTPUT_FILE="$OUTPUT_DIR/factor_research_charts.zip"

		;;


	research-groups)

		HTTP_METHOD="GET"

		ENDPOINT="/backtest/factor-research/groups"

		OUTPUT_TYPE="json"

		DEFAULT_OUTPUT_FILE="$OUTPUT_DIR/factor_research_groups.json"

		;;


	research-delete)

		HTTP_METHOD="DELETE"

		ENDPOINT="/backtest/factor-research"

		OUTPUT_TYPE="json"

		DEFAULT_OUTPUT_FILE="$OUTPUT_DIR/factor_research_delete.json"

		;;


	/*)

		HTTP_METHOD="${HTTP_METHOD:-GET}"

		ENDPOINT="$ENDPOINT_INPUT"

		OUTPUT_TYPE="${OUTPUT_TYPE:-json}"

		DEFAULT_OUTPUT_FILE="$OUTPUT_DIR/local_endpoint_result.json"

		;;


	*)

		echo
		echo "ERROR: Unknown endpoint:"
		echo
		echo "    $ENDPOINT_INPUT"
		echo

		usage

		exit 1

		;;

esac


# ============================================================
# VALIDATE QUERY ARGUMENTS
#
# After the earlier "shift", "$@" now contains only the
# endpoint's query arguments.
#
# Do not copy these into an empty Bash array. Older macOS Bash
# versions combined with "set -u" can treat expansion of an
# empty array as an unbound variable.
# ============================================================

for argument in "$@"; do

	if [[ "$argument" != *=* ]]; then

		echo
		echo "ERROR: Query arguments must use:"
		echo
		echo "    name=value"
		echo
		echo "Invalid argument:"
		echo
		echo "    $argument"
		echo

		exit 1

	fi

done


# ============================================================
# VALIDATE FILES / DIRECTORIES
# ============================================================

if [[ ! -d "$PROJECT_DIR" ]]; then

	echo
	echo "ERROR: TradingMage project directory not found:"
	echo
	echo "    $PROJECT_DIR"
	echo

	exit 1

fi


if [[ ! -d "$APP_DIR" ]]; then

	echo
	echo "ERROR: TradingMage app directory not found:"
	echo
	echo "    $APP_DIR"
	echo

	exit 1

fi


if [[ ! -f "$APP_DIR/app.py" ]]; then

	echo
	echo "ERROR: app.py not found:"
	echo
	echo "    $APP_DIR/app.py"
	echo

	exit 1

fi


if [[ ! -d "$VENV_DIR" ]]; then

	echo
	echo "ERROR: Python virtual environment not found:"
	echo
	echo "    $VENV_DIR"
	echo

	exit 1

fi


if [[ ! -f "$ENV_FILE" ]]; then

	echo
	echo "ERROR: Local environment file not found:"
	echo
	echo "    $ENV_FILE"
	echo

	exit 1

fi


if [[ ! -f "$SSH_KEY" ]]; then

	echo
	echo "ERROR: SSH key not found:"
	echo
	echo "    $SSH_KEY"
	echo

	exit 1

fi


mkdir -p "$OUTPUT_DIR"


# ============================================================
# LOAD LOCAL ENVIRONMENT
# ============================================================

set -a

source "$ENV_FILE"

set +a


# ============================================================
# CRITICAL SAFETY
#
# app.py startup can start the live trailing-stop position
# manager when this value is true.
#
# Always force it OFF for local backtesting.
# ============================================================

export TRAILING_STOP_EXIT_ENABLED="false"

# ============================================================
# LOCAL RESEARCH FILE
#
# Research endpoint output is intentionally stored locally,
# not inside the EC2 TradingMage container.
# ============================================================

export TV_BACKTEST_FACTOR_RESEARCH_LOG="$RESEARCH_LOG"

export TV_BACKTEST_DIAGNOSTIC_LOG="$OUTPUT_DIR/backtest_trade_diagnostics.csv"

export TV_LIVE_DIAGNOSTIC_LOG="$OUTPUT_DIR/live_trade_diagnostics.csv"

# ============================================================
# CLEANUP
# ============================================================

cleanup() {

	EXIT_STATUS=$?

	echo
	echo "Cleaning up..."


	if [[ -n "${UVICORN_PID:-}" ]]; then

		if kill -0 "$UVICORN_PID" 2>/dev/null; then

			kill "$UVICORN_PID" 2>/dev/null || true

			wait "$UVICORN_PID" 2>/dev/null || true

		fi

	fi


	if [[ -n "${SSH_TUNNEL_PID:-}" ]]; then

		if kill -0 "$SSH_TUNNEL_PID" 2>/dev/null; then

			kill "$SSH_TUNNEL_PID" 2>/dev/null || true

			wait "$SSH_TUNNEL_PID" 2>/dev/null || true

		fi

	fi


	return "$EXIT_STATUS"

}


trap cleanup EXIT INT TERM


# ============================================================
# DISPLAY REQUEST
# ============================================================

echo
echo "============================================================"
echo "TradingMage Local Endpoint Runner"
echo "============================================================"
echo
echo "Method:"
echo
echo "    $HTTP_METHOD"
echo
echo "Endpoint:"
echo
echo "    $ENDPOINT"
echo


# ============================================================
# FIND REDIS CONTAINER IP ON EC2
# ============================================================

echo "Finding Redis container IP on EC2..."


REMOTE_REDIS_IP="$(
	ssh \
		-i "$SSH_KEY" \
		-o BatchMode=yes \
		-o ConnectTimeout=10 \
		"${EC2_USER}@${EC2_HOST}" \
		"sudo docker inspect \
			-f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
			${REMOTE_REDIS_CONTAINER}"
)"


REMOTE_REDIS_IP="$(
	printf '%s' "$REMOTE_REDIS_IP" \
	| tr -d '[:space:]'
)"


if [[ -z "$REMOTE_REDIS_IP" ]]; then

	echo
	echo "ERROR: Unable to determine Redis container IP."
	echo
	echo "Redis container name:"
	echo
	echo "    $REMOTE_REDIS_CONTAINER"
	echo

	exit 1

fi


echo
echo "Redis container IP:"
echo
echo "    $REMOTE_REDIS_IP"
echo


# ============================================================
# START REDIS SSH TUNNEL
# ============================================================

echo "Starting Redis SSH tunnel..."


ssh \
	-i "$SSH_KEY" \
	-N \
	-L "${LOCAL_REDIS_PORT}:${REMOTE_REDIS_IP}:${REMOTE_REDIS_PORT}" \
	-o ExitOnForwardFailure=yes \
	-o ServerAliveInterval=30 \
	-o ServerAliveCountMax=3 \
	"${EC2_USER}@${EC2_HOST}" &


SSH_TUNNEL_PID=$!


sleep 2


if ! kill -0 "$SSH_TUNNEL_PID" 2>/dev/null; then

	echo
	echo "ERROR: Redis SSH tunnel failed to start."
	echo

	exit 1

fi


echo
echo "Redis tunnel established:"
echo
echo "    Mac:"
echo "        127.0.0.1:${LOCAL_REDIS_PORT}"
echo
echo "    EC2 Redis container:"
echo "        ${REMOTE_REDIS_IP}:${REMOTE_REDIS_PORT}"
echo


# ============================================================
# POINT LOCAL app.py TO TUNNELED REDIS
# ============================================================

export REDIS_URL="redis://127.0.0.1:${LOCAL_REDIS_PORT}/${REDIS_DATABASE}"


echo "Local REDIS_URL:"
echo
echo "    $REDIS_URL"
echo


# ============================================================
# ACTIVATE PYTHON ENVIRONMENT
# ============================================================

source "$VENV_DIR/bin/activate"


# ============================================================
# CHECK REQUIRED PACKAGES
# ============================================================

if ! python3 -c \
	"import fastapi, uvicorn, pandas, numpy, redis, alpaca_trade_api, matplotlib, scipy" \
	>/dev/null 2>&1
then

	echo
	echo "ERROR: Required Python packages are missing from:"
	echo
	echo "    $VENV_DIR"
	echo
	echo "Test manually with:"
	echo
	echo "    source \"$VENV_DIR/bin/activate\""
	echo
	echo "    python3 -c 'import fastapi, uvicorn, pandas, numpy, redis, alpaca_trade_api, matplotlib, scipy'"
	echo

	exit 1

fi


# ============================================================
# VERIFY REDIS THROUGH SSH TUNNEL
# ============================================================

echo "Testing Redis tunnel..."


python3 - <<'PY'

import os
import redis


client = redis.Redis.from_url(
	os.environ["REDIS_URL"],
	decode_responses=True,
)


if not client.ping():

	raise RuntimeError(
		"Redis PING returned false"
	)


print(
	"Redis PING successful."
)

PY


# ============================================================
# START ACTUAL app/app.py LOCALLY
#
# --ws none is intentional.
#
# alpaca-trade-api 3.2.0 requires websockets < 11.
# Recent Uvicorn WebSocket implementations expect a newer
# websockets API.
#
# None of these TradingMage backtest endpoints require
# WebSockets, so WebSocket support is disabled.
# ============================================================

rm -f "$UVICORN_LOG"


echo
echo "Starting local TradingMage app.py..."


cd "$APP_DIR"


python3 -m uvicorn app:app \
	--host "$LOCAL_APP_HOST" \
	--port "$LOCAL_APP_PORT" \
	--ws none \
	> "$UVICORN_LOG" \
	2>&1 &


UVICORN_PID=$!


# ============================================================
# WAIT FOR FASTAPI HEALTH CHECK
# ============================================================

APP_READY="false"


for attempt in {1..30}; do

	if curl \
		-sS \
		--fail \
		"http://${LOCAL_APP_HOST}:${LOCAL_APP_PORT}/health" \
		>/dev/null \
		2>&1
	then

		APP_READY="true"

		break

	fi


	if ! kill -0 "$UVICORN_PID" 2>/dev/null; then

		echo
		echo "ERROR: Local FastAPI process exited during startup."
		echo
		echo "Uvicorn log:"
		echo

		cat "$UVICORN_LOG"

		exit 1

	fi


	sleep 1

done


if [[ "$APP_READY" != "true" ]]; then

	echo
	echo "ERROR: Local FastAPI failed its health check."
	echo
	echo "Uvicorn log:"
	echo

	cat "$UVICORN_LOG"

	exit 1

fi


echo
echo "Local TradingMage FastAPI is ready:"
echo
echo "    http://${LOCAL_APP_HOST}:${LOCAL_APP_PORT}"
echo


# ============================================================
# BUILD QUERY STRING
#
# IMPORTANT:
#
# "$@" may legitimately be empty, for example:
#
# ./run_local_endpoint.sh research-groups
#
# Handle that case without expanding an empty Bash array.
#
# Python performs the URL encoding so timestamps containing
# "+", ":", commas, etc. are encoded correctly.
# ============================================================

if [[ $# -eq 0 ]]; then

	QUERY_STRING=""

else

	QUERY_STRING="$(
		python3 - "$@" <<'PY'

import sys
import urllib.parse


pairs = []


for argument in sys.argv[1:]:

	key, value = argument.split(
		"=",
		1,
	)

	pairs.append(
		(
			key,
			value,
		)
	)


print(
	urllib.parse.urlencode(
		pairs
	)
)

PY
	)"

fi


# ============================================================
# BUILD FINAL URL
# ============================================================

URL="http://${LOCAL_APP_HOST}:${LOCAL_APP_PORT}${ENDPOINT}"


if [[ -n "$QUERY_STRING" ]]; then

	URL="${URL}?${QUERY_STRING}"

fi


echo "Calling:"
echo
echo "    $HTTP_METHOD $URL"
echo


# ============================================================
# OUTPUT FILE
#
# Relative OUTPUT_FILE values are automatically placed inside:
#
# TradingMage/local_backtest_output/
#
# Absolute paths are respected as supplied.
# ============================================================

if [[ -n "${OUTPUT_FILE:-}" ]]; then

	if [[ "$OUTPUT_FILE" = /* ]]; then

		:

	else

		OUTPUT_FILE="$OUTPUT_DIR/$OUTPUT_FILE"

	fi

else

	OUTPUT_FILE="$DEFAULT_OUTPUT_FILE"

fi


mkdir -p "$(dirname "$OUTPUT_FILE")"

rm -f "$OUTPUT_FILE"


# ============================================================
# CALL FASTAPI ENDPOINT
# ============================================================

set +e


HTTP_CODE="$(
	curl \
		-sS \
		-X "$HTTP_METHOD" \
		-w "%{http_code}" \
		-o "$OUTPUT_FILE" \
		"$URL"
)"


CURL_STATUS=$?


set -e


# ============================================================
# CURL / TRANSPORT FAILURE
# ============================================================

if [[ "$CURL_STATUS" -ne 0 ]]; then

	echo
	echo "ERROR: curl failed with exit code:"
	echo
	echo "    $CURL_STATUS"
	echo


	if [[ -f "$OUTPUT_FILE" ]]; then

		echo
		echo "Partial response:"
		echo

		cat "$OUTPUT_FILE" || true

		echo

	fi


	echo
	echo "Last 100 lines of local Uvicorn log:"
	echo

	tail -100 "$UVICORN_LOG" || true

	exit "$CURL_STATUS"

fi


echo
echo "HTTP status:"
echo
echo "    $HTTP_CODE"
echo


# ============================================================
# HTTP ERROR
# ============================================================

if [[ "$HTTP_CODE" -lt 200 || "$HTTP_CODE" -ge 300 ]]; then

	echo
	echo "ERROR: Endpoint returned HTTP $HTTP_CODE"
	echo
	echo "Response:"
	echo

	cat "$OUTPUT_FILE" || true

	echo
	echo
	echo "Last 100 lines of local Uvicorn log:"
	echo

	tail -100 "$UVICORN_LOG" || true

	exit 1

fi


# ============================================================
# JSON RESPONSE
# ============================================================

if [[ "$OUTPUT_TYPE" == "json" ]]; then

	echo "JSON saved to:"
	echo
	echo "    $OUTPUT_FILE"
	echo

	if ! python3 -m json.tool "$OUTPUT_FILE" >/dev/null 2>&1; then

		echo
		echo "WARNING: Response is not valid JSON."
		echo

		cat "$OUTPUT_FILE"

	elif [[ "$ENDPOINT_INPUT" == "run" ]]; then

		echo "Valid JSON response received."
		echo
		echo "Full response suppressed from terminal."

	else

		echo "Response:"
		echo

		python3 -m json.tool "$OUTPUT_FILE"

	fi


# ============================================================
# ZIP RESPONSE
# ============================================================

elif [[ "$OUTPUT_TYPE" == "zip" ]]; then

	echo "ZIP saved to:"
	echo
	echo "    $OUTPUT_FILE"
	echo

	if ! unzip -tq "$OUTPUT_FILE" >/dev/null 2>&1; then

		echo
		echo "ERROR: Response is not a valid ZIP archive."
		echo
		echo "Response contents:"
		echo

		cat "$OUTPUT_FILE" || true

		exit 1

	fi

	echo "ZIP archive validated successfully."


	if [[ "$EXTRACT_ZIP" == "true" ]]; then

		OUTPUT_DIRECTORY="${OUTPUT_FILE%.zip}"

		rm -rf "$OUTPUT_DIRECTORY"

		mkdir -p "$OUTPUT_DIRECTORY"

		unzip \
			-q \
			"$OUTPUT_FILE" \
			-d "$OUTPUT_DIRECTORY"

		echo
		echo "ZIP extracted to:"
		echo
		echo "    $OUTPUT_DIRECTORY"
		echo


		if [[ \
			"$ENDPOINT_INPUT" == "plot" \
			|| "$ENDPOINT_INPUT" == "research-plot" \
		]]; then

			echo
			echo "Opening backtest charts..."
			echo

			cd "$PROJECT_DIR"

			python3 show_backtest_charts.py "$OUTPUT_DIRECTORY"

		fi

	fi

fi

echo
echo "============================================================"
echo "COMPLETE"
echo "============================================================"